#!/usr/bin/env python3
"""ASP Smart PR: auto-create PR with correct branch, base, and reviewers.

Reads config/surfaces.yaml for surface → repo/branch/reviewer mapping.

Usage:
    python tools/smart_pr.py --issue 42 --surface backend
    python tools/smart_pr.py --issue 42 --surface backend --dry-run
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("Missing PyYAML. Install: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parents[1]
SURFACES_CONFIG = REPO_ROOT / "config" / "surfaces.yaml"


def load_surfaces() -> dict[str, Any]:
    with open(SURFACES_CONFIG, encoding="utf-8") as f:
        return yaml.safe_load(f)


def run(cmd: list[str], *, cwd: Path | None = None, check: bool = True, dry_run: bool = False) -> str:
    display = " ".join(cmd)
    print(f"$ {display}", file=sys.stderr)
    if dry_run:
        print("  [DRY RUN] skipped", file=sys.stderr)
        return ""
    result = subprocess.run(
        cmd, capture_output=True, text=True, cwd=cwd, timeout=60,
        encoding="utf-8", errors="replace",
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"Command failed: {(result.stderr or '').strip()}")
    return (result.stdout or "").strip()


def resolve_surface(surface_name: str, config: dict) -> dict[str, Any]:
    surfaces = config.get("surfaces", {})
    if surface_name not in surfaces:
        available = ", ".join(surfaces.keys())
        raise RuntimeError(f"Unknown surface '{surface_name}'. Available: {available}")
    return surfaces[surface_name]


def main() -> None:
    parser = argparse.ArgumentParser(description="ASP Smart PR")
    parser.add_argument("--issue", type=int, required=True, help="GitHub issue number")
    parser.add_argument("--surface", required=True, help="Surface name (backend, app, admin, etc.)")
    parser.add_argument("--title", help="PR title (default: auto from issue)")
    parser.add_argument("--issue-repo", default="AI-MYG/asp",
                        help="Repo to look up issue title (default: AI-MYG/asp)")
    parser.add_argument("--model", help="Model that implemented the change (shown in PR body)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    config = load_surfaces()
    surface = resolve_surface(args.surface, config)
    branch_pattern = config.get("branch_pattern", "issue-{issue_number}/{surface}")

    repo = surface["repo"]
    base_branch = surface["base_branch"]
    reviewers = surface.get("default_reviewers", [])
    branch_name = branch_pattern.format(issue_number=args.issue, surface=args.surface)

    # PR 指派人（assignee）：默认指派给该 surface 的负责人，便于本人跟进。
    # 来源用 default_reviewers（它们是正确的 GitHub 数字 login，如 app/admin 的
    # "1401554949"），而非 team_lead（那是 "hujianfei" 这种名字，不是 GitHub
    # login，gh --assignee 会失败）。assignee 与 reviewer 不同：可以指给自己。
    assignees = list(reviewers)

    # 剔除 PR 作者本人（仅针对 reviewer）：GitHub 不允许请求自己 review 自己的
    # PR，否则 gh pr create 的 reviewer 请求会报错。assignee 不受此限制，保留。
    # 当 lead 自己既是 operator 又是 default_reviewer 时（如 admin/app），
    # 这一步避免无意义的自我 review 请求。best-effort：查不到就保持原样。
    try:
        self_login = run(["gh", "api", "user", "--jq", ".login"])
        if self_login:
            filtered = [r for r in reviewers if r != self_login]
            if len(filtered) != len(reviewers):
                print(f"已从 reviewers 中剔除 PR 作者本人 ({self_login})", file=sys.stderr)
            reviewers = filtered
    except RuntimeError as e:
        print(f"无法解析当前用户，reviewers 保持原样：{e}", file=sys.stderr)

    # 人类可读的提示一律打到 stderr，stdout 只保留最后那段纯 JSON，
    # 否则 Pipeline D（issue_executor）用 json.loads(proc.stdout) 解析会失败，
    # 导致拿不到 pr_url（日志里显示 "PR 已创建：unknown"）。
    print(f"Surface: {args.surface}", file=sys.stderr)
    print(f"Repo: {repo}", file=sys.stderr)
    print(f"Base branch: {base_branch}", file=sys.stderr)
    print(f"PR branch: {branch_name}", file=sys.stderr)
    print(f"Reviewers: {reviewers}", file=sys.stderr)
    print(f"Assignees: {assignees}", file=sys.stderr)

    # Get issue title for PR title
    pr_title = args.title
    if not pr_title:
        raw = run(["gh", "issue", "view", str(args.issue), "-R", args.issue_repo, "--json", "title"])
        if raw:
            issue_data = json.loads(raw)
            pr_title = f"[ASP-{args.issue}] {issue_data.get('title', '').replace('[feishu] ', '')}"
        else:
            pr_title = f"[ASP-{args.issue}] {args.surface}"

    # Create PR
    model_line = f"\n\n**Implemented by**: `{args.model}`" if args.model else ""
    # Use "Closes" only when PR repo matches issue repo (GitHub auto-close);
    # otherwise "References" (cross-repo links don't auto-close).
    link_verb = "Closes" if repo == args.issue_repo else "References"
    pr_body = f"{link_verb} {args.issue_repo}#{args.issue}{model_line}\n\n🤖 Generated by Pipeline D (Smart PR)"
    pr_cmd = [
        "gh", "pr", "create",
        "-R", repo,
        "--base", base_branch,
        "--head", branch_name,
        "--title", pr_title,
        "--body", pr_body,
    ]
    for reviewer in reviewers:
        pr_cmd.extend(["--reviewer", reviewer])
    for assignee in assignees:
        pr_cmd.extend(["--assignee", assignee])

    result = run(pr_cmd, dry_run=args.dry_run)

    output = {
        "surface": args.surface,
        "repo": repo,
        "base_branch": base_branch,
        "branch": branch_name,
        "reviewers": reviewers,
        "assignees": assignees,
        "pr_url": result if result else "(dry-run)",
    }
    print(json.dumps(output, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
